language: python
python:
  - "3.6"
before_install:
  - pip install pipenv==2018.10.13
install:
  - pipenv install --dev --system --deploy
  - python manage.py migrate
  - python manage.py collectstatic
script:
  - python manage.py test
